### PR TITLE
Removed

### PR DESCRIPTION
**Pull request by Alcazer**
I deleted them all, thanks for the interest.

### CODE REVIEW

**Comment by CrackzNovitch** [comment]
Hello you can compile ?

**Comment by Alcazer** [comment]
> Hello you can compile ?

Yes [PaliaHook-v0.178.1.zip](#out-of-update)

**Comment by Mag-mil-r** [comment]
This seems to crash when loading between zones.

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000

PaliaHook!SDK::InSDKUtils::GetVirtualFunction<void (__cdecl*)(SDK::UObject const *,SDK::UFunction *,void *)>() [C:\Users\redacted\source\repos\PaliaHook2\PaliaSDK\SDK\Basic.hpp:52]
PaliaHook!SDK::UObject::ProcessEvent() [C:\Users\redacted\source\repos\PaliaHook2\PaliaSDK\SDK\CoreUObject_classes.hpp:75]
PaliaHook!SDK::AActor::K2_GetActorLocation() [C:\Users\redacted\source\repos\PaliaHook2\PaliaSDK\SDK\Engine_functions.cpp:4065]
PaliaHook!DrawHUD() [C:\Users\redacted\source\repos\PaliaHook2\PaliaHook\PaliaOverlay.cpp:448]
PaliaHook!ProcessEvent() [C:\Users\redacted\source\repos\PaliaHook2\PaliaHook\PaliaOverlay.cpp:561]
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
kernel32
ntdll

To be clear this is on @Alcazer fork, also happens on the above dll provided by Alcazer.

**Comment by Alcazer** [comment]
> This seems to crash when loading between zones.
> 
> Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000
> 
> PaliaHook!SDK::InSDKUtils::GetVirtualFunction<void (__cdecl*)(SDK::UObject const *,SDK::UFunction *,void *)>()
> 
> To be clear this is on @Alcazer fork, also happens on the above dll provided by Alcazer.

Getting access error when changing map because pointer is reset. As a quick fix, turn off esp when changing maps.

I'll solve it as soon as I have time

**Comment by Alcazer** [comment]
> This seems to crash when loading between zones.
> 
> Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000
>  PaliaHook!SDK::AActor::K2_GetActorLocation()  
> To be clear this is on @Alcazer fork, also happens on the above dll provided by Alcazer.

@Mag-mil-r  Can you try again?

The problem seems to be solved for me and doesnt give an error

**Comment by Alcazer** [comment]
> > Hello you can compile ?
> 
> Yes [PaliaHook-v0.178.1.zip](#out-of-update)

@CrackzNovitch updated version [PaliaHook-v.0.178.1-5166957.dll.zip](#out-of-update)

**Comment by Mag-mil-r** [comment]
Yes that seemed to have fixed it, thank you.

**Comment by BryanWai** [comment]
> _ No description provided. _

Thank you.
Are you using Dumper-7?

**Comment by Alcazer** [comment]
> > _ No description provided. _
> 
> Thank you. Are you using Dumper-7?

Yes ([Dumper-7](https://github.com/Encryqed/Dumper-7))

**Comment by Alcazer** [comment]
Updated release [PaliaHook-v.0.179.0-09cec22.dll.zip](https://github.com/klukule/PaliaHook/files/15102442/PaliaHook-v.0.179.0-09cec22.dll.zip)

**Comment by Alcazer** [comment]
@klukule Can you approve it?

**Comment by Alcazer** [comment]
Updated release [PaliaHook-v.0.179.0-47e6dd9.dll.zip](#out-of-update)

@klukule Can you approve it?

**Comment by BryanWai** [comment]
> Updated release [PaliaHook-v.0.179.0-47e6dd9.dll.zip](https://github.com/klukule/PaliaHook/files/15103050/PaliaHook-v.0.179.0-47e6dd9.dll.zip)
> 
> @klukule Can you approve it?

I don't think the author will update anymore.
BTW I want to add some new features.
I have sent you email but no reply.
I wonder if you could help?

**Comment by Alcazer** [comment]
> > Updated release [PaliaHook-v.0.179.0-47e6dd9.dll.zip](https://github.com/klukule/PaliaHook/files/15103050/PaliaHook-v.0.179.0-47e6dd9.dll.zip)
> > @klukule Can you approve it?
> 
> I don't think the author will update anymore. BTW I want to add some new features. I have sent you email but no reply. I wonder if you could help?

I guess

>I'm trying to write a new hack to put furniture anywhere, or clipping furniture at the same place.
>Could you please give me some advice?

Your mail is marked as spam. I just saw it. Some information is available on the UC site. Please check and search the UC Palia forum. Force Item Placement, Reversal, Structs and Offsets etc. may be helpful.

**Comment by Mag-mil-r** [comment]
Been getting semi frequent crashes with these 2 things - case EType::Ore:
	if (AnyTrue2D(Ores)) {
		STATIC_CLASS("BP_ValeriaGatherableLoot_Mining_Base_C");
	}
	break; 

and

case EType::Forage:
	if (AnyTrue2D(Forageables)) {
		STATIC_CLASS("BP_Valeria_Gatherable_Placed_C");
	}
	break; 

- edit --
- seems to be hitting on a lot of the different actor type switches.
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x000002cbc0c13890

PaliaHook!SDK::UObject::IsValidLowLevel() [C:\Users\redacted\Documents\GitHub\PaliaHook-Alcazar\PaliaSDK\SDK\CoreUObject_classes.hpp:33]
PaliaHook!PaliaOverlay::ProcessActors() [C:\Users\redacted\Documents\GitHub\PaliaHook-Alcazar\PaliaHook\PaliaOverlay.cpp:241]
PaliaHook!DrawHUD() [C:\Users\redacted\Documents\GitHub\PaliaHook-Alcazar\PaliaHook\PaliaOverlay.cpp:447]
PaliaHook!ProcessEvent() [C:\Users\redacted\Documents\GitHub\PaliaHook-Alcazar\PaliaHook\PaliaOverlay.cpp:568]
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
kernel32
ntdll
@Alcazer

**Comment by Alcazer** [comment]
> Been getting semi frequent crashes with these 2 things - case EType::Ore: if (AnyTrue2D(Ores)) { STATIC_CLASS("BP_ValeriaGatherableLoot_Mining_Base_C"); } break;
> 
> and
> 
> case EType::Forage: if (AnyTrue2D(Forageables)) { STATIC_CLASS("BP_Valeria_Gatherable_Placed_C"); } break;
> 
> * edit --
> * seems to be hitting on a lot of the different actor type switches.
>   Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x000002cbc0c13890
> 

I didn't have much time so I couldn't try it, but maybe the latest commit 643cf13 will work for you @Mag-mil-r

**Comment by Alcazer** [comment]
> Been getting semi frequent crashes with these 2 things - case EType::Ore: if (AnyTrue2D(Ores)) { STATIC_CLASS("BP_ValeriaGatherableLoot_Mining_Base_C"); } break;
> 
> and
> 
> case EType::Forage: if (AnyTrue2D(Forageables)) { STATIC_CLASS("BP_Valeria_Gatherable_Placed_C"); } break;
> 
> * edit --
> * seems to be hitting on a lot of the different actor type switches.
>   Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x000002cbc0c13890
> 

I didn't have much time so I couldn't try it, but maybe the latest commit 43aabcd will work for you @Mag-mil-r 

Can you write the result here?

If this is not enough, please try again by changing line 30 of CoreUObject_classes.hpp as follows
```
bool IsValidLowLevel() {
	if (this == nullptr)
		return false;
	if (IsBadReadPtr(Class, sizeof(UClass)))
		return false;
	if (!Class)
		return false;
	if (IsBadReadPtr(GObjects, sizeof(TUObjectArray)))
		return false;
	if (!GObjects)
		return false;
	return GObjects->GetByIndex(Index) == this;
}
```

**Comment by Mag-mil-r** [comment]
I tried the new commit, seemed to be better(not as frequent) but didn't get a ton of time to test it, however it did still result in a crash.  I missed copying the stack but this was one of the lines- 	auto GameInstance = World->OwningGameInstance;   I tried adding the above code to CoreUObject_classes.hpp and it will not build - Line 33 Use of underfined type 'SDK::UClass' - 	if (IsBadReadPtr(Class, sizeof(UClass))).  

Thanks again @Alcazer

**Comment by Alcazer** [comment]
> I tried the new commit, seemed to be better(not as frequent) but didn't get a ton of time to test it, however it did still result in a crash. I missed copying the stack but this was one of the lines- auto GameInstance = World->OwningGameInstance; I tried adding the above code to CoreUObject_classes.hpp and it will not build - Line 33 Use of underfined type 'SDK::UClass' - if (IsBadReadPtr(Class, sizeof(UClass))).
> 
> Thanks again @Alcazer

Please change the if (IsBadReadPtr(Class, sizeof(UClass))) to if (IsBadReadPtr(Class, 512)) and check again?

**Comment by Alcazer** [comment]
> I tried the new commit, seemed to be better(not as frequent) but didn't get a ton of time to test it, however it did still result in a crash. I missed copying the stack but this was one of the lines- auto GameInstance = World->OwningGameInstance; I tried adding the above code to CoreUObject_classes.hpp and it will not build - Line 33 Use of underfined type 'SDK::UClass' - if (IsBadReadPtr(Class, sizeof(UClass))).
> 
> Thanks again @Alcazer

Please check again? @Mag-mil-r

**Comment by Mag-mil-r** [comment]
Loaded it up and crashed on second load in, this might be worse, home -> bahari -> home (crash) 3x in a row.
	if (IsBadReadPtr(Class, 512)) -> 	STATIC_CLASS("BP_ValeriaBugCatchingCreature_C"); -> 
auto GameInstance = World->OwningGameInstance; -> OriginalProcEvent(Class, Function, Params);

**Comment by Alcazer** [comment]
> ```
> Loaded it up and crashed on second load in, this might be worse, home -> bahari -> home (crash) 3x in a row.	if (IsBadReadPtr(Class, 512)) -> 	STATIC_CLASS("BP_ValeriaBugCatchingCreature_C"); -> auto GameInstance = World->OwningGameInstance; -> OriginalProcEvent(Class, Function, Params);
> ```

I think the problem is with PendingKill function. Maybe this problem is unreal engine related.
https://issues.unrealengine.com/issue/UE-175302
This page says Target Fix 5.5 version

--

I don't think this will be related to our code. Since esp is running, that function name appears in the last process.

Currently, i don't know for now why the error occurred, but maybe it can be solved in the future.

You will get crash when you open cheat engine (or other tools) and change the map after changing the location, or you will get the same crash when you change the map after changing the walk speed.

```
Fatal error: [File:D:\shared\Palia\Palia-release_0.179.0_filtered\Engine\Source\Runtime\CoreUObject\Private\UObject\ReferenceChainSearch.cpp] [Line: 1947]
Fatal world leaks detected. Logging first error, check logs for additional information
(PendingKill) (async) ... bla bla bla
```

**Comment by Mag-mil-r** [comment]
Interesting, just seems to be particularly bad since the 179 update. Thanks for looking into this, have you thought about allowing issues on your fork, or even making a new repo, since the original author seems to be MIA?

**Comment by Alcazer** [comment]
> Interesting, just seems to be particularly bad since the 179 update.

I have no idea about this, because i don't play

> Thanks for looking into this, have you thought about allowing issues on your fork, or even making a new repo, since the original author seems to be MIA?

I'm sure that @klukule has seen these comments but I can't prove it :)

Honestly, I haven't thought about it because it's not my project and I don't know what the future holds.

I've been updating it for a couple of versions just so my son can use esp. Because finding gatherable items is hard for a 4 year old without esp.

I did some research and found MultiHack in UC Forum, he used it a few times, but when the new version came, the developer was updating it very late. 

And finally I found this repository open source and I updated it to work on the latest version. Totally depends on my son, maybe in the future I won't update it at all and if he gets bored playing palia he will delete it and I will stop updating.

That's all for now

**Comment by Mag-mil-r** [comment]
Seems with the latest commits, some things are not showing up anymore on ESP, like flow trees occasionally .  @Alcazer

**Comment by Alcazer** [comment]
Which version are you using? I looked with my son and checked with Palia Map. It looks like there is no problem with the ee60ff4 version. And he's been playing for five or six hours. He didn't get any error. Can you show me which ones are not working properly? @Mag-mil-r 

ss 2024-04-27 211248

**Comment by Alcazer** [comment]
@Mag-mil-r  Please try new version 1cb2c08. to avoid crash i added a 30 second cooldown after the world changes, maybe this will solve EXCEPTION_ACCESS_VIOLATION

**Comment by klukule** [comment]
Hey there, sorry for the inactivity...

I've been really swamped with work IRL + it's been many months since I last even opened palia :) I prefer to test anything I merge into this repo first, so I'll merge this hopefully next week, though do not expect active development from me any time soon as IRL work keeps killing me.

I will leave this PR open at least until I merge it, but feel free to continue development on your own fork as you see fit (if there's somthing interesting you wish to merge into this repo, just open up a PR)

**Comment by klukule** [comment]
Also as Alcazer pointer out, I am reading these comments (and I get notified about every single comment) but as I've said in my previous comment, I'm just really busy to put it mildly.

**Comment by Alcazer** [comment]
Hi @klukule thanks for coming back, no problem as I mentioned in my previous comments. When I saw that it was open source, I updated it as requested by my son and it works in the latest version of the game. I added some features from other programs like MultiHack. I will add a few more features as I get the time (Auto fishing and auto sell fish etc.) I used [Dumper-7 64fa89c](https://github.com/Encryqed/Dumper-7/commit/64fa89cafe88d30dde8474a7f0c5caa7c457d482) on the palia login screen to update the SDK.

**Comment by Mag-mil-r** [comment]
> @Mag-mil-r Please try new version [1cb2c08](https://github.com/klukule/PaliaHook/commit/1cb2c080466f921007f4e83812306fa06fcae5ff). to avoid crash i added a 30 second cooldown after the world changes, maybe this will solve EXCEPTION_ACCESS_VIOLATION

I will give this a try a bit later thanks, the issue i was having with the flow trees might have just been a glitch. I relogged and i've gotten them to work, previous to that they were working about 70% before the relog.  Thanks!

**Comment by Alcazer** [comment]
> I will give this a try a bit later thanks, the issue i was having with the flow trees might have just been a glitch. I relogged and i've gotten them to work, previous to that they were working about 70% before the relog. Thanks!

I've been testing myself for about 2 hours, relogged several times, never encountered the scenario you mentioned.

ss-2024-04-27 230732

**Comment by Mag-mil-r** [comment]
Yeah I haven't run into the flow tree issue again so chalk that up to it just being fickle that time. I've tried your latest with the 30 second delay, still crashes, but just about 30 seconds after loading into the level now. Thanks for all your work you two!

**Comment by Alcazer** [comment]
Today I had a try on a different computer and yes sometimes it crashes. When I searched for the problem, I found IsPendingKill and K2_DestroyActor functions. It is crashing due to garbage collection.

https://dev.epicgames.com/documentation/en-us/unreal-engine/API/Runtime/CoreUObject/UObject/UObjectBaseUtility/IsPendingKill?application_version=5.0
This page says;
> Deprecated with UE 5.0 version * IsPendingKill() should no longer be used.

As I mentioned in previous comments
> 
> I think the problem is with PendingKill function. Maybe this problem is unreal engine related. https://issues.unrealengine.com/issue/UE-175302 This page says Target Fix 5.5 version
> 
> --
> 
> I don't think this will be related to our code. Since esp is running, that function name appears in the last process.
> 
> Currently, i don't know for now why the error occurred, but maybe it can be solved in the future.
> 
> You will get crash when you open cheat engine (or other tools) and change the map after changing the location, or you will get the same crash when you change the map after changing the walk speed.
> 
> ```
> Fatal error: [File:D:\shared\Palia\Palia-release_0.179.0_filtered\Engine\Source\Runtime\CoreUObject\Private\UObject\ReferenceChainSearch.cpp] [Line: 1947]
> Fatal world leaks detected. Logging first error, check logs for additional information
> (PendingKill) (async) ... bla bla bla
> ```

and IsValidLowLevel already exists on UObject
https://dev.epicgames.com/documentation/en-us/unreal-engine/API/Runtime/CoreUObject/UObject/UObjectBase/IsValidLowLevel?application_version=5.0
This page says;
> UObjectBase::IsValidLowLevel
> Checks to see if the object appears to be valid true if this appears to be a valid object

When you search for "IsValidLowLevel crash", there are similar problems that have happened before.

I think I solved it in the last commit ( 48353cb )

**Comment by Alcazer** [comment]
@Mag-mil-r Could you please test it?

**Comment by Alcazer** [comment]
@Mag-mil-r Could you please test it?

**Comment by Mag-mil-r** [comment]
Yes I will try to test it today, with the hotfix yesterday morning i was not able to get in before the servers went down.

**Comment by grapha855** [comment]
@Alcazer @Mag-mil-r Any chance someone could compile it so I can inject it and try? I don't know how to compile the files into a .dll.

**Comment by xNightJade** [comment]
Still crashes even with it turned off, tried going to bahari from kilima and it kept crashing

**Comment by Alcazer** [comment]
> Still crashes even with it turned off, tried going to bahari from kilima and it kept crashing

Crashes are located in the following folders;
`%LocalAppData%\Palia\Saved\Crashes`
or
`install folder\Palia\Saved\Crashes`

@OfficialModdz Can you tell us more about?

As I mentioned in previous comments
> Maybe this problem is unreal engine related.

> You will get crash when you open cheat engine (or other tools) and change the map after changing the location, or you will get the same crash when you change the map after changing the walk speed.

> Fatal error: [File:D:\shared\Palia\Palia-release_0.179.0_filtered\Engine\Source\Runtime\CoreUObject\Private\UObject\ReferenceChainSearch.cpp] [Line: 1947]
> Fatal world leaks detected. Logging first error, check logs for additional information
> (PendingKill) (async) ... bla bla bla

**Comment by Mag-mil-r** [comment]
Was able to play with it a bit , I did end up with 1 crash which was a lot less then before. This happened while i was in a level not switch between levels. Had been running around for 15-20 minutes in Bihari when it happened. Thanks again!

aliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaHook!SDK::InSDKUtils::CallGameFunction<void (__cdecl*)(SDK::UObject const *,SDK::UFunction *,void *),SDK::UObject const *,SDK::UFunction * &,void * &>() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaSDK\SDK\Basic.hpp:63]
PaliaHook!SDK::UObject::ProcessEvent() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaSDK\SDK\CoreUObject_classes.hpp:68]
PaliaHook!SDK::AActor::K2_GetActorLocation() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaSDK\SDK\Engine_functions.cpp:6304]
PaliaHook!DrawHUD() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaHook\PaliaOverlay.cpp:490]
PaliaHook!ProcessEvent() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaHook\PaliaOverlay.cpp:631]

**Comment by Alcazer** [comment]
> Was able to play with it a bit , I did end up with 1 crash which was a lot less then before. This happened while i was in a level not switch between levels. Had been running around for 15-20 minutes in Bihari when it happened. Thanks again!
> 
> PaliaClient_Win64_Shipping PaliaClient_Win64_Shipping PaliaHook!SDK::InSDKUtils::CallGameFunction<void (__cdecl*)(SDK::UObject const *,SDK::UFunction *,void *),SDK::UObject const *,SDK::UFunction * &,void * &>() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaSDK\SDK\Basic.hpp:63] PaliaHook!SDK::UObject::ProcessEvent() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaSDK\SDK\CoreUObject_classes.hpp:68] PaliaHook!SDK::AActor::K2_GetActorLocation() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaSDK\SDK\Engine_functions.cpp:6304] PaliaHook!DrawHUD() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaHook\PaliaOverlay.cpp:490] PaliaHook!ProcessEvent() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaHook\PaliaOverlay.cpp:631]

I think it is related to Player, it was deleted from the memory just when it was trying to get the location information, so it gave an error.

I added new commit 944f04a. Please try with latest commit.

**Comment by Alcazer** [comment]
> Was able to play with it a bit , I did end up with 1 crash which was a lot less then before. This happened while i was in a level not switch between levels. Had been running around for 15-20 minutes in Bihari when it happened. Thanks again!
> 
> PaliaClient_Win64_Shipping PaliaClient_Win64_Shipping PaliaHook!SDK::InSDKUtils::CallGameFunction<void (__cdecl*)(SDK::UObject const *,SDK::UFunction *,void *),SDK::UObject const *,SDK::UFunction * &,void * &>() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaSDK\SDK\Basic.hpp:63] PaliaHook!SDK::UObject::ProcessEvent() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaSDK\SDK\CoreUObject_classes.hpp:68] PaliaHook!SDK::AActor::K2_GetActorLocation() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaSDK\SDK\Engine_functions.cpp:6304] PaliaHook!DrawHUD() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaHook\PaliaOverlay.cpp:490] PaliaHook!ProcessEvent() [C:\Users\redacted\Documents\GitHub\PaliaHook-ALZ-latest\PaliaHook\PaliaOverlay.cpp:631]

I think it is related to Player, it was deleted from the memory just when it was trying to get the location information, so it gave an error.

I added new commit e3bd7be. Please try with latest commit.  K2_GetActorLocation function was edited by klukule after generating the SDK with Dumper-7, I missed it.

> // HACK: Skip actors that return [0,0,0] due to the hack I had to add to K2_GetActorLocation
> if (!this) return {}; // TODO: Figure this one out... as before calling this function the actor is valid and passes all checks, but inside the body it's nullptr

It may solve the problem to use `Actor->RootComponent->RelativeLocation;` instead of `Actor->K2_GetActorLocation();`

**Comment by Alcazer** [comment]
> @Alcazer @Mag-mil-r Any chance someone could compile it so I can inject it and try? I don't know how to compile the files into a .dll.

@grapha855 updated version [PaliaHook-v.0.179.1-e3bd7be.dll.zip](#out-of-update)

**Comment by grapha855** [comment]
@Alcazer I downloaded the .dll and tried injecting it at the login screen with both Cheat Engine, and Extreme Injector. It successfully injects, and I can open the menu with F12. I tried enabling options, but nothing ever displays. I've tried adjusting everything in the menu and can't get it to display anything. Thank you for your help. Im not sure what I'm doing wrong.

**Comment by Alcazer** [comment]
> I downloaded the .dll and tried injecting it at the login screen with both Cheat Engine, and Extreme Injector. It successfully injects, and I can open the menu with F12. I tried enabling options, but nothing ever displays. I've tried adjusting everything in the menu and can't get it to display anything. Thank you for your help. Im not sure what I'm doing wrong.

If you send a video, maybe we can solve the problem

**Comment by Alcazer** [comment]
I added new features related to fishing ( a727b09 ).

Best usage;
Capture best fishing spot
Go and open General Store
Dont forget to buy worms
Tick Instant fishing, Perfrect Catch, No Rod Rurability Loss, Sell fish, Destroy Others and Override spot
Go any fishing spot
Tick auto fishing and set global game speed 15
Remember; Currently you can deposit a maximum of 300,000 gold coins and maximum of 4,000 worms in your inventory.
(Fishing rod must be equipped for see the settings)
Enjoy yourself

**Comment by Rxstar-sq** [comment]
Sorry I am confused but how to compile it into .dll agian?

**Comment by BryanWai** [comment]
> I added new features related to fishing ( [a727b09](https://github.com/klukule/PaliaHook/commit/a727b099f5fb22fd3144f341ac66e7488dd33177) ).
> 
> Best usage; Capture best fishing spot Go and open General Store Dont forget to buy worms Tick Instant fishing, Perfrect Catch, No Rod Rurability Loss, Sell fish, Destroy Others and Override spot Go any fishing spot Tick auto fishing and set global game speed 15 Remember; Currently you can deposit a maximum of 300,000 gold coins and maximum of 4,000 worms in your inventory. (Fishing rod must be equipped for see the settings) Enjoy yourself

Thanks for your work!

I tried to use the auto fishing feature without instant fishing, but it doesn't work.
And if you also turn on perfect catch, the game will crash.

**Comment by Alcazer** [comment]
I will add steam support soon.

> > I added new features related to fishing ( [a727b09](https://github.com/klukule/PaliaHook/commit/a727b099f5fb22fd3144f341ac66e7488dd33177) ).
> > Best usage; Capture best fishing spot Go and open General Store Dont forget to buy worms Tick Instant fishing, Perfrect Catch, No Rod Rurability Loss, Sell fish, Destroy Others and Override spot Go any fishing spot Tick auto fishing and set global game speed 15 Remember; Currently you can deposit a maximum of 300,000 gold coins and maximum of 4,000 worms in your inventory. (Fishing rod must be equipped for see the settings) Enjoy yourself
> 
> Thanks for your work!
> 
> I tried to use the auto fishing feature without instant fishing, but it doesn't work. And if you also turn on perfect catch, the game will crash.

Which version are you using? I can't help you unless you send video of the error and a crash report.

**Comment by Alcazer** [comment]
> Sorry I am confused but how to compile it into .dll again?

Searching "cmake build tutorial" may be helpful

**Comment by BryanWai** [comment]
> I will add steam support & some fixes related to automatic fishing soon.
> 
> > > I added new features related to fishing ( [a727b09](https://github.com/klukule/PaliaHook/commit/a727b099f5fb22fd3144f341ac66e7488dd33177) ).
> > > Best usage; Capture best fishing spot Go and open General Store Dont forget to buy worms Tick Instant fishing, Perfrect Catch, No Rod Rurability Loss, Sell fish, Destroy Others and Override spot Go any fishing spot Tick auto fishing and set global game speed 15 Remember; Currently you can deposit a maximum of 300,000 gold coins and maximum of 4,000 worms in your inventory. (Fishing rod must be equipped for see the settings) Enjoy yourself
> > 
> > 
> > Thanks for your work!
> > I tried to use the auto fishing feature without instant fishing, but it doesn't work. And if you also turn on perfect catch, the game will crash.
> 
> Which version are you using? I can't help you unless you send video of the error and a crash report.

I think there should only be one commit since you have added the fishing feature.
I'm not really using the fishing function cause in my opinion instant fishing is already out of the scope of 'soft-hack'.
To reproduce it you can simply try to turn on auto fishing and perfect catch.

**Comment by Alcazer** [comment]
> > I will add steam support & some fixes related to automatic fishing soon.
> > > > I added new features related to fishing ( [a727b09](https://github.com/klukule/PaliaHook/commit/a727b099f5fb22fd3144f341ac66e7488dd33177) ).
> > > > Best usage; Capture best fishing spot Go and open General Store Dont forget to buy worms Tick Instant fishing, Perfrect Catch, No Rod Rurability Loss, Sell fish, Destroy Others and Override spot Go any fishing spot Tick auto fishing and set global game speed 15 Remember; Currently you can deposit a maximum of 300,000 gold coins and maximum of 4,000 worms in your inventory. (Fishing rod must be equipped for see the settings) Enjoy yourself
> > > 
> > > 
> > > Thanks for your work!
> > > I tried to use the auto fishing feature without instant fishing, but it doesn't work. And if you also turn on perfect catch, the game will crash.
> > 
> > 
> > Which version are you using? I can't help you unless you send video of the error and a crash report.
> 
> I think there should only be one commit since you have added the fishing feature. I'm not really using the fishing function cause in my opinion instant fishing is already out of the scope of 'soft-hack'. To reproduce it you can simply try to turn on auto fishing and perfect catch.

There is no details in the readme file. It only says soft hack. Can you explain what soft-hack means? Which features should or should not be there? It's easy to remove "soft" in README or revert whatever has been changed or added. I can remove all of them if you wish

**Comment by Alcazer** [comment]
Oh no @klukule already said it in UC forum. I missed that.
> While I won't be actively developing the hack, I plan to update the SDK occasionally, at least for a little while. If you've got contributions you think would fit, don't hesitate to send a pull request my way. Just a heads up: I'm primarily looking for soft-hack related enhancements. Avoid submissions related to teleportation, server crashes, etc. as I will not merge these.

That's enough.

**Pull request closed without merging**
