### PR TITLE
ESP Improvements

### PR DESCRIPTION
**Pull request by Estyms**
- Hide gatherables when collected
- Changed name of Tree and Nodes category to Harvestable
- Fixed spice toggle

### CODE REVIEW

**Comment by klukule** [comment]
Regarding gatherable vs harvestable... I used internal names for everything and since palia calles it Gatherable I used that (same with Cearnuk vs Sernuk). This is just FYI. Originally had plans to rename everything properly (including creature names etc...)

Do you have any other changes planned as part of the PR, or should I merge it?

**Comment by sucrettae** [comment]
Yeah, I do have found a way to hide the esp when the plant collected is in spectral form, as well as a properly working spice toggle as it didn't work at all before

**Comment by klukule** [comment]
Yep yep, I read through the code... the question was more about whether you want to add more as part of this PR or whether I should merge it now and you potentially create another PR later down the line.

**Comment by sucrettae** [comment]
Oh, sorry I misunderstood
I don't really have any other ideas to add for now, so you can close the pull request

**Pull request merged**
